### ISSUE TITLE
it does NOT work with www

### ISSUE THREAD

**Issue by thanhthang20** [sindresorhus/get-urls#10] opened 2015-08-13 07:06 UTC
can not detect url without http
ex: www.simplecrew.com

**Comment by kevva** [comment] 2015-08-13 07:16
https://github.com/kevva/url-regex/issues/12

**Comment by sindresorhus** [comment] 2015-08-13 07:25
@kevva That issue was regarding without both `http` and `www`. It can easily detect `www` domains without the TLD list, and it should.

**Comment by kevva** [comment] 2015-08-13 07:46
I don't really like that behaviour. Like, protocols are mandatory IF you aren't using `www` in the beginning of your URL. I rather just force protocols.

**Comment by sindresorhus** [comment] 2015-08-13 08:32
> Like, protocols are mandatory IF you aren't using www in the beginning of your URL.

Yes, but he *is* using `www`.

**Comment by kevva** [comment] 2015-08-13 09:21
Yeah, but I think it's a weird behavior.

**Comment by sindresorhus** [comment] 2015-08-13 09:42
Why is it weird behaviour? I honestly don't see the issue here.

**Comment by thanhthang20** [comment] 2015-08-13 09:48
@kevva , @sindresorhus Your module can not detect the url start with 'www' (ex: www.simplecrew.com). So I have to use RegEx instead of your module. Just make clear my problem, thanks!

**Comment by sindresorhus** [comment] 2015-11-01 09:32
ping @kevva :)

**Comment by kevva** [comment] 2015-11-06 10:53
I meant that the weird behavior is caused by accepting URLs with `www` and no protocol but forcing a protocol if no `www` is provided. But I guess that's just me :P.

**Comment by sindresorhus** [comment] 2015-11-06 17:41
@kevva Think of it more like "best effort" matching. With `www` we can be sure it's an URL, same with `http`.

**Comment by radiovisual** [comment] 2016-06-08 11:13
Any movement on this? I would like to help, but I don't have enough free time to dive head-first into a massive regular expression. I see that the problem actually lies in the [url-regex](https://github.com/kevva/url-regex) dependency, and the issue has [already been reported there](https://github.com/kevva/url-regex/issues/17).

**Comment by sindresorhus** [comment] 2016-06-08 11:50
// @kevva

**Comment by kevva** [comment] 2016-06-08 12:15
Fixed in https://github.com/kevva/url-regex/commit/6ece341f88383bce3a4969f4417fa615f1c0ea9d.

**Closed by kevva** 2016-06-08 12:15 UTC
