### ISSUE TITLE
CommonJS version?

### ISSUE THREAD

**Issue by ArtuGit** [sindresorhus/get-urls#83] opened 2022-06-02 17:08 UTC
Is there CommonJS version?
With `const getUrls = require('get-urls')`
I have `Error [ERR_REQUIRE_ESM]: require() of ES Module /<...> not supported.`

**Comment by sindresorhus** [comment] 2022-06-03 05:08
Duplicate of #82

**Closed by sindresorhus** 2022-06-03 05:08 UTC
