### ISSUE TITLE
Invalid results when urls are surrounded by double quotes

### ISSUE THREAD

**Issue by dylang** [sindresorhus/get-urls#11] opened 2015-12-03 23:02 UTC
## Example input
```
<script src="https://example1.com/script1.js?querystring=true"></script>
<script src="https://example2.com/script2.js"></script>
```

## Expected result

```
[ 'http://example1.com/script1.js?querystring=true',
  'http://example2.com/script2.js ]
```

## Actual Results

```
[ 'http:///%22https:/example1.com/script1.js?querystring=true"',
  'http:///%22https:/example2.com/script2.js%22' ]
```

* `//` becomes `///%22https:/`
* double quote remaining at end of string with the querystring
* `%22` at the end without a querystring

## Note

HTML is not a regular language so it can't be parsed by regular expressions, so addressing this issue might be outside of the scope of this project. 

A possible "fix" is just updating the readme with a warning about using this library with HTML. `¯\_(ツ)_/¯`

I'm going to try solving what I was attempting to do using the DOM.

**Comment by dylang** [comment] 2015-12-03 23:08
### Addendum

The same unexpect results happen with the doublequotes but no HTML:

```
> getUrls('"https://example1.com/script1.js?querystring=true" "https://example2.com/script2.js"')
[ 'http:///%22https:/example1.com/script1.js?querystring=true"',
  'http:///%22https:/example2.com/script2.js%22' ]
```

Replacing the double quotes with spaces addresses this issue.

```
> get('<script src= https://example1.com/script1.js?querystring=true ></script>
<script src= https://example2.com/script2.js ></script>')
[ 'https://example1.com/script1.js?querystring=true',
  'https://example2.com/script2.js' ]
```

**Comment by sindresorhus** [comment] 2015-12-04 11:02
The problem is that https://github.com/kevva/url-regex returns the URLs with quotes and this module runs those through https://github.com/sindresorhus/normalize-url, which expects valid URLs (without quotes) and borks it up. The correct solution would be to make `url-regex` not match the quotes. I would open an PR/issue there about fixing it.

**Comment by joakimbeng** [comment] 2015-12-04 18:33
Ran into this myself...

> I would open an PR/issue there about fixing it

I just did :)

**Comment by dylang** [comment] 2015-12-04 18:43
Thanks @joakimbeng and @sindresorhus.

**Comment by kevva** [comment] 2016-04-13 14:29
Fixed in https://github.com/kevva/url-regex/commit/e8b20d54779c8626fc371112be097eac00a3dda5.

**Closed by kevva** 2016-04-13 14:29 UTC
Labels: bug
